FROM alpine
MAINTAINER leman

## add package
ADD nginx-1.16.1.tar.gz /home

RUN sed -i  's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g'  /etc/apk/repositories  &&  apk update \
apk add gcc g++  pcre-dev  openssl-dev zlib-dev make \
&&  cd  /home/nginx-1.16.1 \
&&  ./configure --prefix=/usr/local/nginx  --with-http_stub_status_module --with-http_ssl_module \
&&  make  \
&& make install \
&& ln -s  /usr/local/nginx/sbin/nginx /usr/sbin/nginx \
&& rm -rf  /home/nginx-1.16.1

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
