FROM ubuntu
MAINTAINER leman

ADD   jdk1.8.0_172.tar.gz  /usr/local/java
RUN   ln -s  /usr/local/java/jdk1.8.0_172  /usr/local/java/jdk

ENV  JAVA_HOME /usr/local/java/jdk
ENV  JRE_HOME ${JAVA_HOME}/jre
ENV  CLASSPATH  .:${JAVA_HOME}/lib:${JRE_HOME}/lib
ENV  PATH  ${JAVA_HOME}/bin:$PATH